### ISSUE TITLE
难以置信，只有一人维护

### ISSUE THREAD

**Issue by uwings** [briansun/chinese-tripitaka-api#2]
🙏 有幸看到 deerpark ，赶紧注册了 deer.land 域名。感觉是目前做的最好的电子经书了，我也有类似的打算，确实现在经书的编排易读性有改进的空间。 

今天似乎看到还有生僻字未正确显示的问题，自己也在做一些epub，同样也遇到用哪些字体比较庄严啊之类的问题，刚看到您的博文，又伸手党了，希望有机会多多交流。

**Comment by 950020** [comment]
师兄啊，东林寺正在招募 epub 制作人员。师兄若有发心，可以参加啊。
他们制作的很精美，也通过东林寺流通，比我们民间制作epub弘法要方便得多。
他们的网站是 donglin.org

**Comment by uwings** [comment]
> 师兄啊，东林寺正在招募 epub 制作人员。师兄若有发心，可以参加啊。
> 他们制作的很精美，也通过东林寺流通，比我们民间制作epub弘法要方便得多。
> 他们的网站是 donglin.org

我在群里的 - -#

**Comment by briansun** [comment]
謝謝各位！

**Comment by jhonnybail** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Prometheo, @nolatercn, @chenxhong, @J-LingShan, @spiniron, @5ime, @ABBOOT, @ATrnd, @2023638537, @asir6, @kkjj5566123, @cwxsss, @King-fly, @tianzeteam, @PlanetApostle, @CoderSerio, @Hzvr, @qq29oo, @qiweiii, @sugarf0528, @yuuuuu422, @xiabee, @LeanMind, @mrchenmo, @jmp0x7c00, @l0z0l, @ruuderie, @YougaKing, @wgqzlj, @simuty, @CharAznableKKK, @fantasybei, @paranoia445, @lijiangze666, @zzzzail, @UpwardGrowth, @hily520, @erDuo10, @RikiRiki8471, @JorjanLLT, @Cafexss, @alazycoder101, @yaozhou, @dotponder, @picaiq, @Onurakdeniz, @0xJchen, @kidneyweakx, @mQxz, @scutdk
